Feature/models
wecode-bootcamp-korea/32-1st-boyFriends-backend pull request #1
Opened 2022-04-26 07:42 UTC by BDjaekwanee

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [x] 리팩토링
- [x] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- ERD를 바탕으로 models 생성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

2. 로그인 데이터 처리 (예시 - 백엔드)
- 사이즈, 재고 :manytomany 로 관리
- 카트 테이블 생성, 결제에 대한 세분화
- 저장 자료형 변환(int -> varchar (테이블만 보고도 정보 알 수 있게 하기위함))

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 테이블 정규화 개념에 대한 이해를 높임.
- ERD 작성법(one -to-one, one-to-many, many-to-many)에 대한 이해도를 높임.
- 같은 테이블을 바라보는 Foreign Key가 다수 있으면 related name 속성을 이용해야 된다는 것을 알게됨.

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-04-26 08:42 UTC, kyeongraekim requested changes
아래내용 확인 후 수정해주세요!~

2022-04-26 08:42 UTC, kyeongraekim commented on payments/models.py
> +    count   = models.IntegerField()
Integerfield() 외에도 PositiveIntegerField()가 있음을 확인하고 해당내용 리서치후 적용여부 검토해주세요

2022-04-26 08:42 UTC, kyeongraekim commented on payments/models.py
> +    order_shipment    = models.ForeignKey("OrderShipment", on_delete=models.CASCADE)
on_delete의 목적, 기능을 한 번 떠올려서 삭제시 작용되는 연쇄 결과들을 미리 고민해보세요

2022-04-26 08:42 UTC, kyeongraekim commented on payments/models.py
> +    order_number = models.CharField(max_length=50)
uuid 에 해당하는 난수를 적용하실 거면 uuidfield 사용도 한 번 검토해보세요

2022-04-26 08:42 UTC, kyeongraekim commented on payments/models.py
> +    tracking_number = models.CharField(max_length=50)
이곳도 혹시 주문 번호와 같이 난수화 과정시 uuid를 사용하시게 되면 필드 속성을 바꿔주심이 좋곘네요!

2022-04-26 11:16 UTC, BDjaekwanee commented on payments/models.py
> +    count   = models.IntegerField()
PositiveIntegerField()가 숫자 0이 포함될까? 라는 생각에 장고 공식문서에서 확인해본 결과 숫자 0도 포함된다고 해서 바로 수정 반영하였습니다.

2022-04-26 11:17 UTC, jiggyjiggy commented on payments/models.py
> +    tracking_number = models.CharField(max_length=50)
order_number에서 uuid를 적용해봤기에 
tracking_number에는 unique=True를 적용해봤습니다

2022-04-26 11:18 UTC, jiggyjiggy commented on payments/models.py
> +    order_number = models.CharField(max_length=50)
uuid를 적용해봤고 유일값이기에 PK로써 사용해봤습니다

2022-04-26 11:22 UTC, BDjaekwanee commented on payments/models.py
> +    order_shipment    = models.ForeignKey("OrderShipment", on_delete=models.CASCADE)
검색 결과  on_delet 를 사용하여 데이터베이스 상에서 참조무결성을 유지하여 ForeignKeyField가 바라보는 값이 삭제될 때  처리하는 방법을 지정해 줄 수 있는 것을 알게 되었습니다.  삭제시 작용되는 연쇄 결과를 고려하여 PROTECT, SET_NULL , DO_NOTHING을 활요해 보았습니다.

2022-04-27 02:00 UTC, kyeongraekim requested changes

2022-04-27 02:00 UTC, kyeongraekim commented on payments/models.py
> +    id           = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False) # order_number
불필요한 주석 제거해주세요, 그리고 order_number라는 의도가 있으시다면 변수명도 그에 맞게 작성해주셔야합니다

2022-04-27 02:00 UTC, kyeongraekim commented on payments/models.py
> +    user         = models.ForeignKey("users.User", on_delete=models.DO_NOTHING)
실제로 user가 삭제 됬을 때 do_nothing 설정을 하시면 user_id 필드값에은 삭제된 그 user.id 값이 적혀있을 것이니 데이터의 무결성을 해칠 가능성이 높아질 겁니다. nullable 하게 기획을 변경해보세요.

2022-04-27 02:00 UTC, kyeongraekim commented on payments/models.py
> +    product           = models.ForeignKey("products.Product", on_delete=models.DO_NOTHING)
이곳도 DO_NOTHING 설정이 보이네요!

2022-04-27 02:00 UTC, kyeongraekim commented on products/models.py
> +    sale     = models.PositiveIntegerField(null=True)
이곳에서의 sale은 혹시 판매수량을 의미하는 건가요?

2022-04-27 02:00 UTC, kyeongraekim commented on products/models.py
> +    stars   = models.PositiveIntegerField()
rating 또는 star_rating 이 더 맞는 표현이 되겠네요!

2022-04-27 04:25 UTC, jiggyjiggy reviewed
SCV 작성하다보니 null값을 줘야 하는 field가 추가로 존재 하는 걸 확인하였습니다 
추가로 수정해서 push 하겠습니다!

2022-04-27 04:25 UTC, jiggyjiggy commented on payments/models.py
> +    user         = models.ForeignKey("users.User", on_delete=models.DO_NOTHING)
회원탈퇴시에도 기존 주문 이력은 남는게 맞다 생각해서
user 정보가 삭제되어도 orders의 row가 삭제되지 않도록 기획해봤습니다
좋지 않은 기획일까요?

2022-04-27 04:25 UTC, jiggyjiggy commented on products/models.py
> +    sale     = models.PositiveIntegerField(null=True)
할인을 생각하고 sale로 설정했었습니다
discount로 수정해 보겠습니다

2022-04-27 04:25 UTC, jiggyjiggy commented on payments/models.py
> +    product           = models.ForeignKey("products.Product", on_delete=models.DO_NOTHING)
상품 정보가 삭제되어도 주문중의 정보가 사라지면 안된다고 생각해서 do nothing처리해봤습니다
혹시 제가 on_delete에 대한 속성 이해를 잘 못 하고있는 걸까요?

2022-04-27 04:25 UTC, jiggyjiggy commented on products/models.py
> +    stars   = models.PositiveIntegerField()
그런 것 같습니다
수정해보겠습니다!

2022-04-27 04:25 UTC, jiggyjiggy commented on payments/models.py
> +    id           = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False) # order_number
id 를 order_number로 수정하고 주석을 지우겠습니다

2022-04-27 09:39 UTC, kyeongraekim approved these changes
LGTM!~ 추후 모델링 수정 기획이 생기면 새로운 feature 모델링 브랜치를 파서 푸시해주세요~

2022-04-27 09:39 UTC, merged